import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#8bd6b6",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "secondary-fixed": "#b0f0d6",
        "on-secondary-fixed": "#002117",
        primary: "#004532",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#95d3ba",
        "tertiary-fixed-dim": "#ffb3ac",
        background: "#f9f9ff",
        "surface-container-highest": "#d8e3fb",
        secondary: "#2b6954",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#263143",
        "on-secondary-container": "#306d58",
        "tertiary-container": "#823f3a",
        "primary-fixed": "#a6f2d1",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#8bd6b6",
        "on-tertiary-fixed-variant": "#73332f",
        "on-background": "#111c2d",
        "secondary-container": "#adedd3",
        "on-secondary-fixed-variant": "#0b513d",
        error: "#ba1a1a",
        "on-primary-fixed": "#002116",
        surface: "#f9f9ff",
        "on-primary-container": "#8bd6b7",
        tertiary: "#652925",
        "outline-variant": "#bec9c2",
        "surface-container": "#e7eeff",
        "on-surface-variant": "#3f4944",
        "on-tertiary-container": "#ffb4ad",
        "inverse-on-surface": "#ecf1ff",
        "surface-bright": "#f9f9ff",
        "surface-container-high": "#dee8ff",
        "on-error": "#ffffff",
        "surface-variant": "#d8e3fb",
        "surface-container-low": "#f0f3ff",
        "primary-container": "#065f46",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#00513b",
        "tertiary-fixed": "#ffdad6",
        "on-tertiary-fixed": "#3b0908",
        "surface-dim": "#cfdaf2",
        "surface-tint": "#1b6b51",
        "on-surface": "#111c2d",
        outline: "#6f7973",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-md": "16px",
        gutter: "16px",
        "container-margin": "32px",
        "stack-lg": "24px",
        base: "4px",
        "stack-sm": "8px",
      },
      fontFamily: {
        "data-mono": ["var(--font-inter)", "monospace"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        display: ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        display: [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
export default config;
